name: Build, Push to Docker Hub, and Deploy to Linode

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: chris2750/dls-exam-example:latest

      # Step 4: Copy docker-swarm.yml to Linode
      - name: Copy docker-swarm.yml to Linode
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          source: ./docker-swarm.yml  # Path to the file in your repo
          target: /home/${{ secrets.LINODE_USER }}/deploy/  # Path where you want the file to go

      # Step 5: Deploy the stack
      - name: Deploy to Linode Docker Swarm
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            echo "Pulling the latest image from Docker Hub..."
            docker pull chris2750/dls-exam-example:latest
            echo "Removing old stack (if exists)..."
            docker stack rm dotnet-app-stack || true
            sleep 5  # Small delay to ensure the stack is removed
            echo "Deploying the new stack..."
            docker stack deploy -c /home/${{ secrets.LINODE_USER }}/deploy/docker-swarm.yml dotnet-app-stack
            echo "Deployment successful!"
